from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetHealthStatus200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, timestamp=None):  # noqa: E501
        """GetHealthStatus200Response - a model defined in OpenAPI

        :param status: The status of this GetHealthStatus200Response.  # noqa: E501
        :type status: str
        :param timestamp: The timestamp of this GetHealthStatus200Response.  # noqa: E501
        :type timestamp: datetime
        """
        self.openapi_types = {
            'status': str,
            'timestamp': datetime
        }

        self.attribute_map = {
            'status': 'status',
            'timestamp': 'timestamp'
        }

        self._status = status
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'GetHealthStatus200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getHealthStatus_200_response of this GetHealthStatus200Response.  # noqa: E501
        :rtype: GetHealthStatus200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this GetHealthStatus200Response.


        :return: The status of this GetHealthStatus200Response.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this GetHealthStatus200Response.


        :param status: The status of this GetHealthStatus200Response.
        :type status: str
        """

        self._status = status

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this GetHealthStatus200Response.


        :return: The timestamp of this GetHealthStatus200Response.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this GetHealthStatus200Response.


        :param timestamp: The timestamp of this GetHealthStatus200Response.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
