openapi: 3.0.3
info:
  title: MEMTEST-API - OpenAPI 3.0
  description: This is the API Used in the memtest-app
  contact:
    email: christopher.witzl@gmx.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: result
    description: Everything about the results of the finished tests
    
paths:
  /result:
    post:
      tags:
        - result
      description: uploads a single test result
      operationId: uploadTestResult
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestResult'
      responses:
        '200':
          description: Successful upload

components:
  schemas:
    TestResult:
      type: object
      properties:
        testdatetime:
          type: string
          format: date-ti/TestResult
