openapi: 3.0.3
info:
  title: MEMTEST-API - OpenAPI 3.0
  description: This is the API Used in the memtest-app
  contact:
    email: christopher.witzl@gmx.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://192.168.178.187:8080/api/v1
tags:
  - name: result
    description: Everything about the results of the finished tests
  - name: health
    description: Health check for the application

paths:
  /result:
    post:
      tags:
        - result
      description: uploads a single test result
      operationId: api.test_result.upload_test_result
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestResult'
      responses:
        '200':
          description: Successful upload
  /health:
    get:
      tags:
        - health
      summary: Health check endpoint
      description: Checks if the server is up and running
      operationId: api.health.health_check
      responses:
        '200':
          description: Service is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'ok'

components:
  schemas:
    TestResult:
      type: object
      properties:
        testdatetime:
          type: string
          format: date-time
